version: '3.8'

services:
  task-management-tests:
    build: .
    container_name: task-management-test-container
    command: java -cp /app/out:/app/libs/junit-4.13.2.jar:/app/libs/hamcrest-core-1.3.jar org.junit.runner.JUnitCore TaskManagerTest
